name: hover_effect
description: Takes any child witget and enables Hover/Tilt 3D functionality to it.
version: 1.0.0+1
homepage: https://github.com/mkiisoft/hover_effect

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
